#!/usr/bin/env python

## @package core
#. This package is the core application of the 
#  state machine

import rospy
import signal
import baxter_gbi_input_msgs.msg as bgi_io
import smach
from std_srvs.srv import Trigger, TriggerResponse
import threading
from gbi_states import *
from graphviz import Digraph

##  class FSMThread 
#   inerithed form threaing.Thread 
class FSMThread(threading.Thread):
    ## the constructor
    def __init__(self):
        threading.Thread.__init__(self)
        
        smach.set_loggers(smach.loginfo,smach.logwarn,self.logdebug,smach.logerr)

        ## attribute to manage the graph in graphviz
        self.f = Digraph('finite_state_machine', filename='state_machine.gv')
        self.f.attr(rankdir='TD', size="30",splines=None)
        self.f.attr('node', shape='circle',style='filled')
        self.f.format="pdf"
        ## sm instance of the container StateMachine with outome=EXIT
        self.sm = smach.StateMachine(outcomes=['EXIT'])
        self.event = FsmEvent()
        self.sm.register_transition_cb(self.transition_cb)
        self.sm.set_initial_state(['INIT'])
        with self.sm:
            smach.StateMachine.add('INIT', InitState(),
                                    transitions={'config_available':'CONFIG',
                                                'config_missing':'WAIT_CONFIG',
                                                'preempted':'EXIT'})

            smach.StateMachine.add('CONFIG', ConfigState(bgi_io.signal, self.action_cb),
                                    transitions={'invalid':'WAIT_CONFIG',
                                                'success':'WAIT_USER',
                                                'preempted':'EXIT'})
            smach.StateMachine.add('WAIT_CONFIG', WaitConfigState(self.event),
                                    transitions={'config_available':'CONFIG',
                                                 'preempted':'EXIT'})
            smach.StateMachine.add('WAIT_USER', WaitUserState(self.event),
                                    transitions={'reconf_requested':'CONFIG',
                                                'user_detected':'MAIN_MENU',
                                                'preempted':'EXIT'})
            smach.StateMachine.add('MAIN_MENU', MainMenuState(self.event),
                                    transitions={'user_missed':'WAIT_USER',
                                                'play_selected':'MENU_PLAY',
                                                'record_selected':'MENU_RECORD',
                                                'macro_selected':'MENU_MACRO',
                                                'sequence_selected':'MENU_SEQUENCE',
                                                'selection':'MAIN_MENU',
                                                'preempted':'EXIT'})
            smach.StateMachine.add('MENU_PLAY', PlayMenuState(self.event),
                                    transitions={'user_missed':'WAIT_USER',
                                                'selection':'PLAY',
                                                'back':'MAIN_MENU',
                                                'remove': 'REMOVE_MENU_PLAY',
                                                'preempted':'EXIT'},
                                    remapping={'filename':'sm_data'})
            smach.StateMachine.add('REMOVE_MENU_PLAY', RemoveMenuState(self.event),
                                    transitions={'user_missed':'WAIT_USER',
                                                 'selection': 'MENU_PLAY',
                                                 'back':'MENU_PLAY',
                                                 'preempted':'EXIT'})
            smach.StateMachine.add('REMOVE_MENU_RECORD', RemoveMenuState(self.event),
                                    transitions={'user_missed':'WAIT_USER',
                                                 'selection':'MENU_RECORD',
                                                 'back':'MENU_RECORD',
                                                 'preempted':'EXIT'})
            smach.StateMachine.add('MENU_RECORD', RecordMenuState(self.event),
                                    transitions={'user_missed':'WAIT_USER',
                                                'selection':'RECORD',
                                                'back':'MAIN_MENU',
                                                'remove':'REMOVE_MENU_RECORD',
                                                'preempted':'EXIT'})
            smach.StateMachine.add('MENU_MACRO', MacroMenuState(self.event),
                                    transitions={'user_missed':'WAIT_USER',
                                                'selection':'SUB_MACRO',
                                                'play':'MACRO',
                                                'back':'MAIN_MENU',
                                                'preempted':'EXIT'})
            smach.StateMachine.add('SUB_MACRO', SubMacroMenuState(self.event),
                                    transitions={'user_missed':'WAIT_USER',
                                                'selection':'MENU_MACRO',
                                                'back':'MENU_MACRO',
                                                'preempted':'EXIT'})
            smach.StateMachine.add('MENU_SEQUENCE',SequenceMenuState(self.event),
                                    transitions={'user_missed':'WAIT_USER',
                                                'selection':'SUB_SEQUENCE',
                                                'play': 'SEQUENCE',
                                                'back':'MAIN_MENU',
                                                'preempted':'EXIT'})
            smach.StateMachine.add('SUB_SEQUENCE', SubSequenceMenuState(self.event),
                                   transitions={'user_missed': 'WAIT_USER',
                                                'selection': 'MENU_SEQUENCE',
                                                'back': 'MENU_SEQUENCE',
                                                'preempted': 'EXIT'})
            smach.StateMachine.add('PLAY', PlayState(self.event),
                                    transitions={'user_missed':'WAIT_USER',
                                                 'done':'MAIN_MENU',
                                                 'preempted':'EXIT'},
                                    remapping={'filename':'sm_data'})
            smach.StateMachine.add('RECORD', RecordState(self.event),
                                    transitions={'user_missed':'WAIT_USER',
                                                 'done':'MAIN_MENU',
                                                 'preempted':'EXIT'})
            smach.StateMachine.add('MACRO', MacroState(self.event),
                                    transitions={'user_missed':'WAIT_USER',
                                                 'done':'MAIN_MENU',
                                                 'preempted':'EXIT'})
            smach.StateMachine.add('SEQUENCE', SequenceState(self.event),
                                    transitions={'user_missed':'WAIT_USER',
                                                 'done':'MAIN_MENU',
                                                'preempted':'EXIT'})
    def logdebug(self,msg):
        pass
   
    ## method register_transition_cb
    #  overide of contaneir.register_transition_cb
    #  @param transition_cb function associating to the transition 
    def register_transition_cb(self, transition_cb): 
        self._transition_cbs.append((transition_cb)) 


    ## method register_transition_cb
    #  @param userdata data of used from the active state
    #  @param active_states list of the active states after the transition
    #  @param *cb_args additional arguments
    def transition_cb(self,userdata,active_states,*cb_args):
        self.f.node_attr.update(color="0.000 1.000 1.000")
        self.f.node(active_states[0],color="0.201 0.753 1.000")
        self.f.render(filename='state_machine',directory=None,view=True,cleanup=True)
        self.f.node(active_states[0],color="0.000 1.000 1.000")
        


    ## method presence_cb
    #  @param msg message of the topic
    #  @param params list of parameters
    def presence_cb(self, msg, params):
        self.event.signal('user_detected')

        #rospy.loginfo("Action %d triggered by the %s:\n%s\n", params["code"], params["topic"], msg)


    ## method action_cb
    #  @param msg message of the topic
    #  @param params list of parameters
    def action_cb(self, msg, params):
        self.event.signal('action_' + str(params["code"]))
        #rospy.loginfo("Action %d triggered by the %s:\n%s\n", params["code"], params["topic"], msg)

    ## method config_cb
    #  @param req rquest from service
    def config_cb(self, req):
        self.event.signal('config')
        #FIXME wait for state machine transition outcome
        return TriggerResponse(success = True, message = "ciao")

    ## method run
    def run(self):
        rospy.Service('config', Trigger, self.config_cb)
        self.sm.execute()
    ## method stop
    def stop(self):
        self.sm.request_preempt()
        while self.sm.is_running(): pass

    ## method graph_gen
    #  graph generation
    def graph_gen(self):
        tr_edge=self.sm.get_internal_edges()
        self.f.node(self.sm.get_initial_states()[0])
        for i in range(0,len(tr_edge)):
            self.f.edge(tr_edge[i][1],tr_edge[i][2],label=tr_edge[i][0])


## function config_server
#  ros node
def config_server():
    t = FSMThread()
    rospy.init_node('config_server')
    t.graph_gen()
    #t.f.render(filename='state_machine',directory=None,view=True,cleanup=True)
    filename = "state_machine.gv"
    '''file = open(filename, "r")
    for line in file:
        print line'''
    t.start()

    rospy.on_shutdown(t.stop)
    rospy.spin()

if __name__ == "__main__":
    config_server()
